export interface DawaBBRBygning {
    ois_id: number;
    ois_ts: string;
    Bygning_id: string;
    Bygningsnr: string;
    ObjStatus: number;
    NyByg: number;
    Crud_id: string;
    Grund_id: string;
    Byggesag_id: string;
    BygStam_id: string;
    AdgAdr_id: string;
    BYG_ANVEND_KODE: number;
    Klassifikation: number;
    AnvKonvKilde: number;
    AntLejMKoekken: number;
    AntLejUKoekken: number;
    OPFOERELSE_AAR: number;
    OMBYG_AAR: number;
    MIDL_OPRET_KODE: number;
    UdloebDatoMidl: string | null;
    BYG_VANDFORSY_KODE: number;
    BYG_AFLOEB_KODE: string | null;
    BYG_AFLOEB_TILL: string | null;
    YDERVAEG_KODE: string;
    TAG_KODE: string;
    SuppYderVaegMat: string;
    SuppTagDaekMat: string | null;
    AsbestMateriale: string | null;
    KILDE_MATR_KODE: string;
    BYG_ARL_SAML: number;
    BYG_BOLIG_ARL_SAML: number;
    ERHV_ARL_SAML: number;
    BYG_BEBYG_ARL: number;
    GARAGE_INDB_ARL: number;
    CARPORT_INDB_ARL: number;
    UDHUS_INDB_ARL: number;
    UDESTUE_ARL: number;
    LukOverdaekAreal: number;
    AFFALDSRUM_ARL: number;
    ANDET_ARL: number;
    OverdaekAreal: number;
    AabenOverdaekAreal: number;
    AdgangsAreal: number;
    Carport_Princip: string | null;
    KILDE_ARL_KODE: number;
    ETAGER_ANT: number;
    ETAGER_AFVIG_KODE: number;
    VARMEINSTAL_KODE: string;
    OPVARMNING_KODE: string | null;
    VARME_SUPPL_KODE: string | null;
    SIKRINGSRUM_ANT: number;
    FREDNING_KODE: string | null;
    BevarVaerdig: string | null;
    UdlejForhold1: string | null;
    HusLeje: number;
    HuslejeOplysDato: string | null;
    SagsType: string;
    BygPktNoejagtigKls: string;
    BygPkt_id: string;
    FOT_id: number;
    StormRaadPaalaeg: number;
    StormRaadPaalaegDato: string | null;
    BygSkadeForsikSelskab: string;
    BygSkadeForsikSelskabDato: string | null;
    KomFelt1: string | null;
    KomFelt2: string | null;
    KomFelt3: string | null;
    KomFelt4: number;
    KomFelt5: number;
    KomFelt6: number;
    JourNr: string | null;
    ESDH_Ref: string | null;
    SikKlas: number;
    OPRET_TS: string;
    AENDR_TS: string;
    Aendr_Funk: string;
    Ophoert_ts: string | null;
    Kommune_id: string;
    KomKode: string;
    eRef: string | null;
    Landsejerlavkode: number;
    KomEjerlavKode: number;
    MatrNr: string;
    ESREjdNr: string;
    Matr_art_kode: number;
    Delnr: string | null;
    Opdelingsnr: string | null;
    BygSkadeOmfatFors: string;
    Gyldighedsdato: string | null;
}
