export interface DawaBBREnhed {
    ois_id: number;
    ois_ts: string;
    Enhed_id: string;
    ObjStatus: number;
    Nybyg: string | null;
    CRUD_ID: string;
    ByggeSag_id: string | null;
    EnhedStam_id: string | null;
    EnhAdr_id: string;
    Etage_id: string;
    Opgang_id: string;
    HenvEnh_id: string | null;
    REF_Enhed_id: string | null;
    ENH_ANVEND_KODE: number;
    Klassifikation: number;
    AnvKonvKilde: number;
    BOLIGTYPE_KODE: string;
    BOLIG_KONDEM: number;
    IdentOpretDato: string | null;
    ENH_ARL_SAML: number;
    BEBO_ARL: number;
    ENH_ERHV_ARL: number;
    KILDE_ARL_KODE: number;
    VAERELSE_ANT: number;
    TOILET_KODE: string;
    BAD_KODE: string;
    KOEKKEN_KODE: string;
    ENERGI_KODE: string | null;
    ENH_UDLEJ1_KODE: string | null;
    HusLeje: number;
    HuslejeOplysDato: string | null;
    AndetAreal: number;
    GodkTomBoligGL: number;
    LOVLIG_ANVEND_KODE: string | null;
    DispTidsbegraensetDato: string | null;
    SagsType: string;
    ENH_DEL_IBRUG_DATO: string | null;
    ENH_UDLEJ2_KODE: string;
    OFF_STOETTE_KODE: string | null;
    IndflytDato: string | null;
    GodkTomBolig: number;
    VARMEINSTAL_KODE: string | null;
    OPVARMNING_KODE: string | null;
    VARME_SUPPL_KODE: string | null;
    FaellesAdgArealAndel: number;
    AabenOverdaekAreal: number;
    LukOverdaekAreal: number;
    VAER_ERHV_ANT: number;
    AntVandskylToilleter: number;
    AntBadevaerelser: number;
    KomFelt1: string | null;
    KomFelt2: string | null;
    KomFelt3: string | null;
    KomFelt4: number;
    KomFelt5: number;
    KomFelt6: number;
    JourNr: string | null;
    ESDH_Ref: string | null;
    SikKlas: number;
    OPRET_TS: string;
    AENDR_TS: string;
    Aendr_Funk: string;
    Ophoert_ts: string | null;
    Gyldighedsdato: string | null;
}
